### PR TITLE
 Fixes for various issues

### PR DESCRIPTION
**Pull request by sanmadjack**
Fixed an issue when null queries were passed to some themes. Just needed the parameter specs changed to allow nulls.

### CODE REVIEW

**Comment by sanmadjack** [comment]
Added a commit that corrects an issue preventing the cron upload from working at all. Then check for if the key wasn't generated never succeeded, so it would never generate the key, which prevents the whole thing from working.

**Comment by sanmadjack** [comment]
Added another commit, to take care of an issue when saving settings in shorthand, like 1M, Since set_int was changed to only accept int it was stripping out the letters, causing settings on the config page to lose that information.

**Comment by sanmadjack** [comment]
Added array_unique to set_tags to prevent primary key violations when upload conflict is set to merge

**Comment by sanmadjack** [comment]
Another commit, this one to take care of an issue with my previous change to prevent cron upload warnings. Since processed items were removed from the queue, comparing the queue length to $i resulted in some items being skipped. Changed the test to just if the length of the queue is greater than 0. Also now using array_pop to pull from the queue (array_shift has an unnecessary performance hit, since the import queue is randomized anyway, and it's imho cleaner than doing it at the end with unset).

**Comment by sanmadjack** [comment]
The changes to cron upload to use RecursiveDirectoryIterator happened to break path-based tag handling, since it removed $subdir from the equation. Since I'm already working on my pull request for merging tag handling, I've gone ahead and just changed cron upload to use the path_to_tags like everything else does, and resolved the issue the lack of $subdir introduced.

**Comment by sanmadjack** [comment]
After switching to develop I found that the new tagging event requires at least a tag or it errors. I didn't want to take the leap of changing some of the image creation logic, so I tested adding the tags immediately upon image creation, rather than right after. This line is from the code that handled image creation:
        $metadata ['tags'] = []; // = $tags; doesn't work when not logged in here
I tried changing it to:
        $metadata ['tags'] = Tag::explode($tags); 
And removing the later tagging step and it seems to be working okay in my tests. I don't know why it was originally commented out like that, if you think it's for a good reason let me know and I'll remove it from this pull request.

**Comment by shish** [comment]
All looks good to me, thanks :D

**Pull request merged**
