### PR TITLE
Adding support for apache 2.4

### PR DESCRIPTION
**Pull request by terokorp**
This requires mod_version installed, but many distributions ship it by default

### CODE REVIEW

**Comment by JarJak** [comment]
but many doesn't... apache 2.4 works fine with Deny from all

**Comment by terokorp** [comment]
http://httpd.apache.org/docs/2.4/mod/mod_access_compat.html
"The directives provided by mod_access_compat have been deprecated by the new authz refactoring. Please see mod_authz_host."

**Comment by HungryFeline** [comment]
No, it doesn't anymore. Apache 2.4.16: ```[...] [core:alert] [...] [...] /srv/www/htdocs/.htaccess: Invalid command 'Deny', perhaps misspelled or defined by a module not included in the server configuration``` and even if it would still work, it's officially obsolete. See https://httpd.apache.org/docs/2.4/upgrading.html#run-time

You could use IfModule. If mod_version is loaded use your code, if not, just the new directives for Apache 2.4. But that could be bad for the performance.

**Comment by terokorp** [comment]
yea, I got that same `Invalid command 'Deny'` and thats why made this patch.
As I wrote to patch message, "Many distributions ship mod_version by default". At first I think to use IfModule but using IfVersion was recommended to use somewhere in apache documets or (comments in there) so I decided to choise mod_version

**Comment by JarJak** [comment]
Why not use both IfModule and IfVersion?

**Comment by HungryFeline** [comment]
That's what I meant with
> If mod_version is loaded use your code

**Comment by terokorp** [comment]
ok, I replaced it with IfModule. using IfModule and ifVersion dosent make sense.

if mod_authz_host or mod_access_compat dosen't have loaded on apache 2.3+ server gives 500 error which is better than giving permission to download database files.
And on 2.2 or lower mod_access have to be loaded or it gives 500 error.

**Comment by JarJak** [comment]
+1 but it needs to te added in readme

**Pull request merged**
