### PR TITLE
Added a list that sorts pictures by views

### PR DESCRIPTION
**Pull request by MetallicAchu**
Most of the code is taken from numeric_score and ported in order to be usable here.
I'm using the "image_views" table and cross-checked it with "images" to make sure that no deleted images are shown.

TODO:

Invoke paginator - for now the list is single-paged only. Meaning that in theory thousands of pictures could be listed.
Showing images based on permissions

### CODE REVIEW

**Comment by MetallicAchu** [comment]
Fixed showing images based on permission.
Would appreciate help using paginator :)

**Comment by sanmadjack** [comment]
@shish re-open this, I typed in the wrong number in the comment

**Comment by MetallicAchu** [comment]
I added an option to show the number of views each image has.
Do I need to reopen the pull request?

**Comment by sanmadjack** [comment]
Yeah, you probably should reopen it

**Comment by damjess** [comment]
We would be interested in using this :)

**Comment by MetallicAchu** [comment]
> We would be interested in using this :)

I created a new pull request #740 
Let me know if you're facing issues implanting it,

Be advised that currently paginator isn't working on my solution, so it will show ALL your pictures based on visits (pictures with 0 visits will be excluded).

**Pull request closed without merging**
